---
- name: Restart the systemd logind
  service:
    name: systemd-logind
    state: restarted
    enabled: yes
- name: Just force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes
