---
- name: Make sure the relevant packages are installed
  become_user: "{{ aur_user }}"
  kewlfft.aur.aur:
    use: yay
    update_cache: yes
    state: present
    extra_args: --useask
    name:
      - seahorse

- name: Create the secret entries for aerc
  command: printf "{{ item.password }}" | secret-tool store --label="{{ item.email }}" email "{{ item.email }}"
  changed_when: false
  loop:
    - {
        email: "{{ user_personal_email }}",
        password: "{{ user_personal_password }}",
      }
    - { email: "{{ user_uni_email }}", password: "{{ user_uni_password }}" }
    - { email: "{{ user_alt_email }}", password: "{{ user_alt_password }}" }
