---
- name: Run the playbook against all hosts
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Install the basic packages
      import_tasks: tasks/packages.yml
      tags:
        - packages

    - name: Perform a system upgrade
      import_tasks: tasks/updatepackages.yml
      tags:
        - packages
        - upgrade
      when: update_system | default(false)

  roles:
    - role: system/systemd
      become: yes
      tags:
        - system
        - systemd
      when: system_systemd_enabled | default(false)

    - role: system/acpid
      become: yes
      tags:
        - systemd
        - acpid
      when: system_acpid_enabled | default(false)

    - role: system/config
      become: no
      tags:
        - system
        - config
      when: system_config_enabled | default(false)

    - role: system/dotfiles
      become: no
      tags:
        - system
        - dotfiles
      when: system_dotfiles_enabled | default(false)

    - role: desktop/entries
      become: yes
      tags:
        - system
        - entries
      when: desktop_entries_enabled | default (false)

    - role: development/docker
      tags:
        - develoopment
        - docker
      when: dev_docker_enabled | default (false)

    - role: quantumfate.zsh
      vars:
        zsh_user: "{{ ansible_user }}"
      tags:
        - zsh
        - dotfiles
      when: zsh_enabled | default(false)

      post_tasks:
        - name: Make sure notifying handlers will run at the end
          import_tasks: tasks/notifier.yml
          tags:
            - notifier
