---
- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Add user user to group docker
  user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: yes
  register: wait_result

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Make sure Docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes