---
- name: Create the systemd conf configuration directory
  file:
    path: "{{ systemd_conf_dir }}"
    state: directory
    owner: "root"
    mode: "0644"
- name: Check if rc.conf exists
  stat:
    path: "{{ systemd_conf_dir }}/{{ systemd_conf_file }}"
  register: systemdconf

- name: Copy the default system.conf file into the configuration directory
  ansible.builtin.copy:
    src: /etc/systemd/systemd.conf
    dest: "{{ systemd_conf_dir }}/{{ systemd_conf_file }}"
    owner: foo
    group: foo
    mode: "0644"
  when: not systemdconf.stat.exists

- name: Set the default timeout for stopping services
  lineinfile:
    dest: "{{ systemd_conf_dir }}/{{ systemd_conf_file }}"
    regexp: "^*DefaultTimeoutStopSec=*s$"
    line: "DefaultTimeoutStopSec=15s"
    backup: true
  when: systemdconf.stat.exists
