---
### This task can be run at the end of a playbook.
### It will trigger events for packages defined
### in roles and handlers when  something needs
### to be done to a configuration that is associated
### installed package.
### ##############################################
### Example use case:
### Ranger can copy its configuration files to
### a user directory to overwrite its own configuration.
### The issue is that when ranger receives a feature update
### that extends its configuration capabilities the new
### feature would be overriden by the current users
### configuration. Therefore after an update we
### need to reconfigure ranger to apply the new configs
### to our user's directory and then we make our changes.

- name: Silently notifying all handlers
  block:
    - name: Notify ranger
      assert: { that: true, quiet: true }
      changed_when: true
      when: "updated_packages.packages is defined and 'ranger' in updated_packages.packages"
      notify:
        - Reconfigure ranger

    - name: Notify git
      assert: { that: true, quiet: true }
      changed_when: true
      when: "updated_packages.packages is defined and 'git' in updated_packages.packages"
      notify:
        - Reconfigure git

    - name: Notify acpid in system
      assert: { that: true, quiet: true }
      changed_when: true
      when: system_acpid_enabled | default(false)
      notify:
        - Restart and enable the acpid

    ### IMPORTANT: Run logind handler at the end when
    ### the playbook will not be excecuted from a node
    ### but on localhost!
    - name: Notify systemd in system
      assert: { that: true, quiet: true }
      changed_when: true
      when: system_systemd_enabled | default(false)
      notify:
        - Just force systemd to reread configs
        - Restart the systemd logind
