---
- name: Run the equivalent of "pacman -Suy" as a separate step
  community.general.pacman:
    update_cache: true
    upgrade: true
  register: changed_packages
  when: update_system | default(false)
  
- name: Set fact variable for changed packages
  set_fact:
    updated_packages: changed_packages
