---
- name: Copy the sddm.conf
  template:
    src: sddm.conf.j2
    dest: /etc/sddm.conf
    owner: root
    mode: u=rw,g=r,o=r

- name: Import bare repo task
  include_tasks: barerepo.yml
  tags:
    - git
    - barerepository

- name: Include symlinc task
  include_tasks: symlinks.yml
  tags:
    - symlinks
