# ZSH config
zsh_export_vars_extras:
  - {
      name: "Java Home",
      variable: "JAVA_HOME",
      value: /usr/lib/jvm/java-17-openjdk,
    }
  - { name: "JDK Home", variable: "JDK_HOME", value: $JAVA_HOME/bin }
  - { name: "Gradle Home", variable: "GRADLE_USER_HOME", value: $HOME/.gradle }
  - { name: "Default editor", variable: "EDITOR", value: "nvim" }
  - { name: "Default editor", variable: "VISUAL", value: "nvim" }
  - {
      name: "Dotbare directory",
      variable: "DOTBARE_DIR",
      value: $HOME/.bare-dotfiles,
    }
  - { name: "Dotbare tree", variable: "DOTBARE_TREE", value: $HOME }
  - { name: "Node version manager", variable: "NVM_DIR", value: "$HOME/.nvm" }

zsh_sources_extras:
  - { name: Custom Functions, path: "$HOME/.scripts/customfunctions" }

zsh_paths_extras:
  - { name: "Java", path: $JAVA_HOME }
  - { name: "All scripts", path: $HOME/.scripts/**/*.sh }

zsh_aliases_extras:
  - {
      alias: "ranger",
      action: 'ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"',
    }
  - { alias: "udot", action: "dotbare add --update" }
  - { alias: "sdot", action: "dotbare status -s" }
  - { alias: "pdot", action: "dotbare push" }

  - { alias: "lsgit", action: "git ls-files" }
  - { alias: "ugit", action: "git add --update" }
  - { alias: "sgit", action: "git status -s" }
  - { alias: "pgit", action: "git push" }
dotfiles_upstream_origin: main

system_user: leonch
home_dir: /home/leonch
