# Geerlingguy roles
# Pip: https://github.com/geerlingguy/ansible-role-pip
pip_package: python-pip
pip_executable: pip
# Docker: https://github.com/geerlingguy/ansible-role-docker
docker_packages: 
  - docker
  - docker-compose
# Zsh: https://github.com/quantumfate/ansible-role-zsh
zsh_personal_config: true