---
- name: Copy ranger configuration files into the user directory
  ansible.builtin.command: ranger --copy-config=all
  register: ranger_output
  changed_when: "'^creating:' in ranger_output.stdout"
- name: Make changes to rc.conf
  block:
    - name: Check if rc.conf exists
      stat: 
        path: "{{ homedir }}.config/ranger/rc.conf"
      register: rcconf
        
    - name: Activate rangers image preview
      lineinfile:
        dest: "{{ homedir }}.config/ranger/rc.conf"
        regexp: '^set preview_images false$'
        line: 'set preview_images true'
      when: rcconf.stat.exists

    - name: Set Ueberzug to be the default image preview
      lineinfile:
        dest: "{{ homedir }}.config/ranger/rc.conf"
        regexp: '^set preview_images_method .*$'
        line: 'set preview_images_method ueberzug'
      when: rcconf.stat.exists